export const posts = [
  {
    id: 1,
    img: "image-currency.jpg",
    author: "Claire Robinson",
    title: "Receive money in any currency with no fees",
    description:
      "The world is getting smaller and we’re becoming more mobile. So why should you be forced to only receive money in a single. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?",
  },
  {
    id: 2,
    img: "image-restaurant.jpg",
    author: "Wilson Hutton",
    title: "Treat yourself without worrying about money",
    description:
      "Our simple budgeting feature allows you to separate out your spending and set realistic limits each month. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?",
  },
  {
    id: 3,
    img: "image-plane.jpg",
    author: "Wilson Hutton",
    title: "Take your Easybank card wherever you go",
    description:
      "We want you to enjoy your travels. This is why we don’t charge any fees on purchases while you’re abroad. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?",
  },
  {
    id: 4,
    img: "image-confetti.jpg",
    author: "Claire Robinson",
    title: "Our invite-only Beta accounts are now live!",
    description:
      "After a lot of hard work by the whole team, we’re excited to launch our closed beta. It’s easy to request an invite through the site. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi est, libero numquam voluptatum aut quisquam, corporis, necessitatibus aliquid vitae ea facere placeat? Et, iste saepe!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dicta dolorum, ut, sit earum vel neque dignissimos repellendus modi perspiciatis, omnis corrupti et vitae veritatis. Numquam repudiandae iure nihil maiores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum eaque nulla eum commodi mollitia nesciunt corrupti esse? Suscipit ea vitae commodi molestiae. Praesentium, tempora minima repellendus placeat rem maxime voluptates suscipit necessitatibus expedita temporibus! Excepturi consequuntur sunt, aliquid vero porro tenetur libero aspernatur. Earum maxime sed vel numquam tempore aut autem corrupti esse impedit expedita, a hic inventore assumenda nulla! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam dolorum itaque, voluptatum nam non officia atque alias laudantium quas architecto minus expedita explicabo perspiciatis voluptate tempora est velit optio quo? At commodi sapiente, doloremque quae quibusdam iure odit doloribus eligendi similique quis, autem aut, incidunt repellat beatae eius voluptates aspernatur quas odio accusantium fugit enim consectetur placeat dolores. Debitis, soluta?",
  },
];
