export const posts = [
  {
    id: 1,
    img: "image-currency.jpg",
    photo: "Chris",
    author: "Claire Robinson",
    date: "3 March 2021",
    title: "Receive money in any currency with no fees",
    description: `\nThe world is getting smaller and we’re becoming more mobile. So why should you be forced to only receive money in a single. 
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.   
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.   
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.   
      `,
  },
  {
    id: 2,
    img: "image-restaurant.jpg",
    photo: "James",
    author: "Wilson Hutton",
    date: "4 March 2021",
    title: "Treat yourself without worrying about money",
    description: `\nOur simple budgeting feature allows you to separate out your spending and set realistic limits each month.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      `,
  },
  {
    id: 3,
    img: "image-plane.jpg",
    photo: "John",
    author: "Wilson Hutton",
    date: "5 March 2021",
    title: "Take your Easybank card wherever you go",
    description: `\nWe want you to enjoy your travels. This is why we don’t charge any fees on purchases while you’re abroad.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.      
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.      
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.      
      `,
  },
  {
    id: 4,
    img: "image-confetti.jpg",
    photo: "Alex",
    author: "Claire Robinson",
    date: "6 March 2021",
    title: "Our invite-only Beta accounts are now live!",
    description: `\nAfter a lot of hard work by the whole team, we’re excited to launch our closed beta. It’s easy to request an invite through the site.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      \n\n\n Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab adipisci magnam, vero exercitationem assumenda error magni sequi amet. Optio consectetur veritatis maiores magni culpa fuga quibusdam odit officia error! Enim.
      `,
  },
];
